metadatos:
  unidad_territorial: "C2"
  distrito: "E2"
  supervisor: "C3"
  fecha: "C4"

estructura_items:
  rangos:
    - { fila_inicio: 9,  fila_fin: 13 }
    - { fila_inicio: 16, fila_fin: 18 }
    - { fila_inicio: 21, fila_fin: 23 }
    - { fila_inicio: 25, fila_fin: 33 }
  col_inicio: 3
  col_fin: 7

limites:
  max_por_item: 2

clasificacion:
  - { max: 10, categoria: "DEFICIENTE" }
  - { max: 20, categoria: "REGULAR" }
  - { max: 30, categoria: "BUENO" }
  - { max: 40, categoria: "EXCELENTE" }

salida:
  carpeta: "data/processed"
  archivo_excel: "anexo2_consolidado.xlsx"

items_nombres:
  ITEM_1: "La programación de actividades del gestor concuerda con su ejecución del mes."
  ITEM_2: "Muestra a los gestores los formatos/herramientas que usa en la supervisión."
  ITEM_3: "Cuenta con evidencia de articular con instituciones para cierre de brechas y gestión de alertas."
  ITEM_4: "Realizó asistencia técnica a sus gestores sobre los resultados de la última supervisión."
  ITEM_5: "Realizó seguimiento y medidas correctivas ante hallazgos de la última supervisión."
  ITEM_6: "Cuenta con programación de hogares priorizados para acompañamiento en excel, foto o pdf."
  ITEM_7: "Realiza la gestión de alertas en el módulo y deriva las alertas con más de 15 días."
  ITEM_8: "Registra en el aplicativo de articulación la actividad desarrollada dentro de las 24 horas."
  ITEM_9: "El hogar manifiesta que se le visitó en el último mes."
  ITEM_10: "El hogar recuerda el tema tratado en la última visita."
  ITEM_11: "El hogar asumió un compromiso en la última visita verificable en cartilla."
  ITEM_12: "Promueve la participación del padre u otro miembro del hogar presente durante la visita."
  ITEM_13: "En la VD, confirma o identifica pre-alertas/alertas sobre salud, violencia, educación u otros."
  ITEM_14: "En la VD, solicita y revisa la tarjeta prenatal/CRED, y DNI del niño(a)."
  ITEM_15: "En la VD, verifica el consumo de hierro (frasco, MMN o tabletas), según corresponda."
  ITEM_16: "En la VD, explora saberes previos mediante preguntas sobre el tema."
  ITEM_17: "En la VD, brinda el tema en la VD según la alerta, edad o etapa de vida del MO."
  ITEM_18: "En la VD, Usa materiales educativos (rotafolio) durante la visita."
  ITEM_19: "En la VD, verifica la comprensión del tema mediante preguntas."
  ITEM_20: "Al finalizar la VD, promueve compromisos y usa la cartilla correspondiente."